services:
    oneup.dca.command.image_optim:
        class: Oneup\DeveloperConvenienceBundle\Command\ImageOptimCommand
        arguments:
            - "@contao.framework"
            - "%kernel.project_dir%"
            - "%developer_convenience.imageoptim.config%"
        tags:
            - { name: 'console.command' }

    oneup.dca.command.sync_project:
        class: Oneup\DeveloperConvenienceBundle\Command\SyncProjectCommand
        arguments:
            - "%contao.web_dir%"
            - "%kernel.project_dir%"
            - "%kernel.root_dir%"
        tags:
            - { name: 'console.command' }

    oneup.dca.command.contao_db_update:
        class: Oneup\DeveloperConvenienceBundle\Command\ContaoDbUpdateCommand
        arguments:
            - "@database_connection"
            - "@oneup.dca.contao.db_update_manager"
            - "@translator"
            - "@contao.doctrine.schema_provider"
        tags:
            - { name: 'console.command' }

    Contao\InstallationBundle\Database\:
        autowire: true
        resource: '../../../../../vendor/contao/installation-bundle/src/Database/Version*'
        tags:
        - { name: 'oneup.dca.contao.db_udpate' }

    oneup.dca.contao.db_update_manager:
        class: Oneup\DeveloperConvenienceBundle\Database\ContaoDatabaseUpdateManager
        public: true
