services:
    _defaults:
        bind:
            $projectDir: '%kernel.project_dir%'
            $uploadPath: '%contao.upload_path%'

    oneup.dca.command.image_optim:
        class: Oneup\DeveloperConvenienceBundle\Command\ImageOptimCommand
        arguments:
            - "@contao.framework"
            - "%kernel.project_dir%"
            - "%developer_convenience.imageoptim.config%"
        tags:
            - { name: 'console.command' }

    oneup.dca.command.sync_project:
        class: Oneup\DeveloperConvenienceBundle\Command\SyncProjectCommand
        arguments:
            - "%contao.web_dir%"
            - "%kernel.project_dir%"
            - "%kernel.root_dir%"
        tags:
            - { name: 'console.command' }
