services:
    oneup.dca.command.image_optim:
        class: Oneup\DeveloperConvenienceBundle\Command\ImageOptimCommand
        tags:
            - { name: 'console.command' }

    oneup.dca.command.sync_project:
        class: Oneup\DeveloperConvenienceBundle\Command\SyncProjectCommand
        tags:
            - { name: 'console.command' }

    oneup.dca.command.contao_db_update:
        class: Oneup\DeveloperConvenienceBundle\Command\ContaoDbUpdateCommand
        tags:
            - { name: 'console.command' }

    Contao\InstallationBundle\Database\:
        autowire: true
        resource: '../../../../../vendor/contao/installation-bundle/src/Database/Version*'
        tags:
        - { name: 'oneup.dca.contao.db_udpate' }

    oneup.dca.contao.db_update_manager:
        class: Oneup\DeveloperConvenienceBundle\Database\ContaoDatabaseUpdateManager
        public: true
